# SPDX-FileCopyrightText: 2024 STRATO AG
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileContributor: Kai Henseler <kai.henseler@strato.de>

FROM reg.1u1.it/docker.io/library/node:24-bookworm

ENV NODE_ENV=development

WORKDIR /app

# await command by podman exec
CMD ["sleep", "infinity"]
