# SPDX-FileCopyrightText: 2024 STRATO AG
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileContributor: Kai Henseler <kai.henseler@strato.de>

FROM node:20-buster

ENV NODE_ENV=development

WORKDIR /app

# await command by podman exec
CMD ["sleep", "infinity"]