name: Header - Code Quality

on:
  push:
    paths:
      - "IONOS/**"

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: cd IONOS/ && npm ci

      - name: Lint Headers
        run: cd IONOS/ && npm run lint

      - name: Prettier
        run: cd IONOS/ && npm run format:check
