name: Header - Build

on:
  pull_request:
    branches:
      - main
    paths:
      - "IONOS/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd IONOS/ && npm ci

      - name: Run lint
        run: cd IONOS/ && npm run lint

      - name: Check if Header was not built
        run: |
          CORE_JS_CHANGES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -e '^core/js/custom-elements/global-navigation/')
          if [[ -n "$CORE_JS_CHANGES" ]]; then
            echo "CORE_JS_CHANGED=true" >> $GITHUB_ENV
          else
            echo "CORE_JS_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Run build
        if: env.CORE_JS_CHANGED == 'false'
        run: cd IONOS/ && npm run build

      - name: Push changes to branch auto-build-${{ github.head_ref }}-output
        if: env.CORE_JS_CHANGED == 'false'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b auto-build-${{ github.head_ref }}-output
          git add core/js/custom-elements/global-navigation/ionos-global-navigation.js
          git commit -sm "build(header): automatic header build ${{ github.head_ref }}"
          git push origin auto-build-${{ github.head_ref }}-output

      - name: Remind to create a pull request
        if: env.CORE_JS_CHANGED == 'false'
        run: |
          Looks like you forgot to build the new header.
          I built it so you can pull it from auto-build-${{ github.head_ref }}-output
