name: Run Tests

on:
  pull_request:
    paths:
      - "IONOS/**"
  push:
    branches:
      - main
    paths:
      - "IONOS/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: cd IONOS/ && npm ci

      - name: Run Tests
        run: cd IONOS/ && npm run test:run

      - name: Run Tests with Coverage
        run: cd IONOS/ && npm run test:coverage